gui:
  nerdFontsVersion: "3"
  scrollHeight: 4

  # Theme macchiato:mauve
  # @see: https://github.com/catppuccin/lazygit/blob/main/themes-mergable/macchiato/mauve.yml
  theme:
    activeBorderColor:
      - '#c6a0f6'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#c6a0f6'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'

  authorColors:
    '*': '#b7bdf8'

os:
  editPreset: 'nvim'
# If true, display a confirmation when subprocess terminates. This allows you to view the output of the subprocess before returning to Lazygit.
promptToReturnFromSubprocess: false
disableStartupPopups: true
