set -g @catppuccin_status_background "none"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_module_bg_color "#{@thm_bg}"

set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_number_position 'left'
set -g @catppuccin_window_text " #{pane_current_command}:#{b:pane_current_path}"
set -g @catppuccin_window_current_text " #[fg=#{@thm_crust}]#{pane_current_command}:#{b:pane_current_path}"
set -g @catppuccin_window_flags "icon" # none, icon, or text
set -g @catppuccin_window_flags_icon_zoom " ()"
set -g @catppuccin_window_current_text_color "#{@thm_mauve}"
set -g @catppuccin_window_text_color "#{@thm_bg}"

set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"

set -g status-right-length 100
set -g status-right "#{E:@catppuccin_status_application}"
if 'test -r /sys/class/power_supply/BAT*' {
  set -ag status-right '#{E:@catppuccin_status_battery}'
}
set -ag status-right "#{E:@catppuccin_status_date_time}"
