#
# ~/.bash_profile
#

# source bashrc if it exists
[[ -f ~/.bashrc ]] && . ~/.bashrc

export TERM='xterm-256color'
export EDITOR='vim'

# set PATH so it includes user's private bin if it exists
if [ -d ~/bin ] ; then
    PATH=~/bin:"${PATH}"
fi
export PATH
