#
# ~/.bash_profile
#

# source bashrc if it exists
[[ -f ~/.bashrc ]] && . ~/.bashrc

export TERM=xterm-256color
export EDITOR=vim

export CLICOLOR=1
#export LSCOLORS=GxFxCxDxBxegedabagaced

# set PATH so it includes user's private bin if it exists
if [ -d ~/bin ] ; then
    PATH="${PATH}":/usr/local/bin:~/bin
fi
export PATH
